name: Scraping Hotel Traveloka

on:
  schedule:
    - cron: '0 1 * * *'  # Setiap hari jam 08.00 WIB (01.00 UTC)
  workflow_dispatch:       # Bisa trigger manual juga

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install playwright beautifulsoup4 pandas
          playwright install chromium
          playwright install-deps chromium

      - name: Run scraper
        run: python scrape_hotel.py

      - name: Upload hasil CSV
        uses: actions/upload-artifact@v3
        with:
          name: hasil-scraping
          path: hotel_bintang4_semarang_lengkap.csv
